# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: commands.proto for package 'commands'

require 'grpc'
require 'commands_pb'

module Commands
  module CommandService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'commands.CommandService'

      rpc :GetCommand, ::Commands::Device, ::Commands::Command
    end

    Stub = Service.rpc_stub_class
  end
end
